Repository AY2324S2-CS2103T-T12-4/tp, pull requests merged in 2024-04, with the labels that each got.

#69 Branch auto complete
  build.gradle
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/CommandData.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/commands/TagCommand.java
  src/main/java/seedu/address/logic/commands/TransactionCommand.java
  src/main/java/seedu/address/ui/CommandBox.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/DarkTheme.css
  src/test/java/seedu/address/logic/MessagesTest.java
  src/test/java/seedu/address/logic/commands/CommandDataTest.java
  src/test/java/seedu/address/logic/commands/TransactionCommandTest.java
  src/test/java/seedu/address/logic/parser/TransactionCommandParserTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/transaction/UniqueTransactionListTest.java
Labels: enhancement

#74 Upgrade GUI
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/java/seedu/address/ui/TransactionCard.java
  src/main/resources/view/CommandBox.fxml
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PersonListCard.fxml
  src/main/resources/view/ResultDisplay.fxml
  src/main/resources/view/TransactionListCard.fxml
Labels: enhancement

#80 Branch update docs
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/CommitActivityDiagram.puml
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/diagrams/UndoRedoState2.puml
  docs/diagrams/UndoRedoState3.puml
  docs/diagrams/UndoRedoState4.puml
  docs/diagrams/UndoRedoState5.puml
  docs/diagrams/UndoSequenceDiagram-Logic.puml
  docs/diagrams/UndoSequenceDiagram-Model.puml
  docs/images/AutoComplete.png
  docs/images/BetterModelClassDiagram.png
  docs/images/CommitActivityDiagram.png
  docs/images/DeleteSequenceDiagram.png
  docs/images/StorageClassDiagram.png
  docs/images/UndoSequenceDiagram-Logic.png
  docs/images/UndoSequenceDiagram-Model.png
  docs/team/dongyoon.md
Labels: documentation

#163 Fix Invalid Datetime Bug
  src/main/java/seedu/address/model/transaction/DateTime.java
  src/test/java/seedu/address/model/transaction/DateTimeTest.java
Labels: bug

#188 Modify PUML in Developer Guide
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/images/ArchitectureSequenceDiagram.png
  docs/images/BetterModelClassDiagram.png
  docs/images/DeleteSequenceDiagram.png
Labels: documentation

#200 Branch extra update
  docs/diagrams/FindEmployeeNameSequenceDiagram.puml
  docs/images/AutoComplete.png
  docs/images/Ui.png
  docs/images/ViewTransaction.png
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/images/payBack_icon.png
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/address/commons/util/AppUtilTest.java
Labels: documentation
